language: node_js
node_js:
- iojs
before_script: npm i -g grunt-cli
after_script: npm run codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/5dfbaf81db46754c2b6b
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: seb.d@mig.me
  api_key:
    secure: QscM8y3mEJCHhuNqoHNA2KC3Ls8nP3S761Jc8PHRkBQ5zR1nQ88WS34EgelOuzZJulXS7/Qu2GSk+9RhUyOrpT+iaGl/2tGmsRIUMdFxLr1q/oINLahYrvprdTFNfGqGcI/MEfF5k49pOaKi/S1MtolctlNStHwpuwBbnoTfsPw=
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
