language: node_js
node_js:
  - iojs
before_script: "npm i -g grunt-cli"
after_script: "npm run codecov"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5dfbaf81db46754c2b6b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
